# Generated by Django 4.2.1 on 2023-06-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('EGP', 'EGP'), ('$', 'USD')], default='EGP', max_length=100),
        ),
    ]
