# Generated by Django 4.2.7 on 2023-11-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_alter_product_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Excel_Visualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
