# Generated by Django 4.2.7 on 2023-11-08 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0003_excel_visualization"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Excel_Visualization",
            new_name="Excel_Visualizations",
        ),
    ]
