# Generated by Django 4.2.7 on 2023-11-08 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0004_rename_excel_visualization_excel_visualizations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="excel_visualizations",
            options={"verbose_name_plural": "Excel Visualizations"},
        ),
    ]
