# Generated by Django 4.2.7 on 2023-11-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0006_plottings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process_Minings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Process_Minings",
            },
        ),
    ]
