# Generated by Django 4.2.7 on 2023-11-24 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0009_welcome_python"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Excel_Visualizations",
            new_name="Security",
        ),
        migrations.RenameModel(
            old_name="Plottings",
            new_name="Visualizations",
        ),
        migrations.DeleteModel(
            name="Welcome_Python",
        ),
        migrations.AlterModelOptions(
            name="security",
            options={"verbose_name_plural": "Security"},
        ),
        migrations.AlterModelOptions(
            name="visualizations",
            options={"verbose_name_plural": "Visualizations"},
        ),
    ]
