# Generated by Django 4.2.7 on 2023-11-24 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0010_rename_excel_visualizations_security_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Visualizations",
            new_name="Visualization",
        ),
        migrations.AlterModelOptions(
            name="visualization",
            options={"verbose_name_plural": "Visualization"},
        ),
    ]
